-- Neovim colors generated by matugen
local colors = {
  primary = "#bbccab",
  on_primary = "#27341d",
  secondary = "#c3c9b9",
  on_secondary = "#2c3227",
  tertiary = "#adcdc7",
  on_tertiary = "#173531",
  primary_container = "#1b2812",
  on_primary_container = "#a5b595",
  secondary_container = "#43493d",
  on_secondary_container = "#dce2d2",
  tertiary_container = "#092925",
  on_tertiary_container = "#96b6b0",
  surface = "#131411",
  on_surface = "#e4e2de",
  surface_container = "#1f201d",
  outline = "#8f9288",
  error = "#ffb4ab",
  tertiary_fixed = "#c8e9e3",
}

return colors
